[workspace]

[package]
name = "debug_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "dist/App.rs"

[dependencies]
wasm-bindgen = "0.2"
omnicraft-runtime = { path = "../crates/omnicraft-runtime" }
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"
